version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: sf
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
  adminer:
    image: adminer:4.7
    restart: always
    ports:
      - 8080:8080

volumes:
  db: {}